# 문서 군집화 (Document Clustering)

- Opinion Review 데이터셋
    - 다양한 주제에 대한 텍스트 리뷰와 의견을 모은 데이터셋
    - https://archive.ics.uci.edu/dataset/191/opinosis+opinion+frasl+review

**데이터셋 구조**

```
OpinosisDataset1.0/
│
├── OpinosisDataset1.1.pdf         # 데이터셋 설명서
│
├── examples/                      # 예제 폴더
│   └─── prepare4rouge/            # 텍스트 요약 평가를 위한 준비 폴더
│       ├── input/                 # 입력 데이터 폴더
│       └── output/                # Rouge 평가 결과 폴더
│
├── scripts/                       # 스크립트 파일 폴더
├── summaries-gold/                # 골드 요약 데이터 모음
└── topics/                        # 주제별 원본 데이터 폴더
    ├── accuracy_garmin_nuvi_255W_gps.txt.data   # Garmin Nuvi 255W GPS의 정확성에 대한 의견
    ├── bathroom_bestwestern_hotel_sfo.txt.data  # Best Western Hotel (San Francisco)의 화장실 관련 의견
    ├── battery-life_amazon_kindle.txt.data      # Amazon Kindle의 배터리 수명에 대한 의견
    ├── battery-life_ipod_nano_8gb.txt.data      # iPod Nano 8GB의 배터리 수명에 대한 의견
    ├── battery-life_netbook_1005ha.txt.data     # ASUS Netbook 1005HA의 배터리 수명에 대한 의견
    ├── buttons_amazon_kindle.txt.data           # Amazon Kindle의 버튼에 대한 의견
    ├── comfort_honda_accord_2008.txt.data       # 2008년형 Honda Accord의 편안함에 대한 의견
    ├── comfort_toyota_camry_2007.txt.data       # 2007년형 Toyota Camry의 편안함에 대한 의견
    ├── directions_garmin_nuvi_255W_gps.txt.data # Garmin Nuvi 255W GPS의 길 안내 성능에 대한 의견
    ├── display_garmin_nuvi_255W_gps.txt.data    # Garmin Nuvi 255W GPS의 디스플레이 성능에 대한 의견
    ├── eyesight-issues_amazon_kindle.txt.data   # Amazon Kindle 사용 중 시력 관련 문제에 대한 의견
    ├── features_windows7.txt.data               # Windows 7의 기능에 대한 의견
    ├── fonts_amazon_kindle.txt.data             # Amazon Kindle의 폰트에 대한 의견
    ├── food_holiday_inn_london.txt.data         # Holiday Inn (London)의 음식에 대한 의견
    ├── food_swissotel_chicago.txt.data          # Swissotel (Chicago)의 음식에 대한 의견
    ├── free_bestwestern_hotel_sfo.txt.data      # Best Western Hotel (San Francisco) 무료 서비스에 대한 의견
    ├── gas_mileage_toyota_camry_2007.txt.data   # 2007년형 Toyota Camry의 연비에 대한 의견
    ├── interior_honda_accord_2008.txt.data      # 2008년형 Honda Accord의 실내 디자인에 대한 의견
    ├── interior_toyota_camry_2007.txt.data      # 2007년형 Toyota Camry의 실내 디자인에 대한 의견
    ├── keyboard_netbook_1005ha.txt.data         # ASUS Netbook 1005HA의 키보드에 대한 의견
    ├── location_bestwestern_hotel_sfo.txt.data  # Best Western Hotel (San Francisco)의 위치에 대한 의견
    ├── location_holiday_inn_london.txt.data     # Holiday Inn (London)의 위치에 대한 의견
    ├── mileage_honda_accord_2008.txt.data       # 2008년형 Honda Accord의 연비에 대한 의견
    ├── navigation_amazon_kindle.txt.data        # Amazon Kindle의 탐색 성능에 대한 의견
    ├── parking_bestwestern_hotel_sfo.txt.data   # Best Western Hotel (San Francisco)의 주차장에 대한 의견
    ├── performance_honda_accord_2008.txt.data   # 2008년형 Honda Accord의 성능에 대한 의견
    ├── performance_netbook_1005ha.txt.data      # ASUS Netbook 1005HA의 성능에 대한 의견
    ├── price_amazon_kindle.txt.data             # Amazon Kindle의 가격에 대한 의견
    ├── price_holiday_inn_london.txt.data        # Holiday Inn (London)의 가격에 대한 의견
    ├── quality_toyota_camry_2007.txt.data       # 2007년형 Toyota Camry의 품질에 대한 의견
    ├── room_holiday_inn_london.txt.data         # Holiday Inn (London)의 객실에 대한 의견
    ├── rooms_bestwestern_hotel_sfo.txt.data     # Best Western Hotel (San Francisco)의 객실에 대한 의견
    ├── rooms_swissotel_chicago.txt.data         # Swissotel (Chicago)의 객실에 대한 의견
    ├── satellite_garmin_nuvi_255W_gps.txt.data  # Garmin Nuvi 255W GPS의 위성 연결 성능에 대한 의견
    ├── screen_garmin_nuvi_255W_gps.txt.data     # Garmin Nuvi 255W GPS의 화면에 대한 의견
    ├── screen_ipod_nano_8gb.txt.data            # iPod Nano 8GB의 화면 성능에 대한 의견
    ├── screen_netbook_1005ha.txt.data           # ASUS Netbook 1005HA의 화면 성능에 대한 의견
    ├── seats_honda_accord_2008.txt.data         # 2008년형 Honda Accord의 좌석에 대한 의견
    ├── service_bestwestern_hotel_sfo.txt.data   # Best Western Hotel (San Francisco)의 서비스에 대한 의견
    ├── service_holiday_inn_london.txt.data      # Holiday Inn (London)의 서비스에 대한 의견
    ├── service_swissotel_hotel_chicago.txt.data # Swissotel (Chicago)의 서비스에 대한 의견
    ├── size_asus_netbook_1005ha.txt.data        # ASUS Netbook 1005HA의 크기에 대한 의견
    ├── sound_ipod_nano_8gb.txt.data             # iPod Nano 8GB의 사운드 성능에 대한 의견
    ├── speed_garmin_nuvi_255W_gps.txt.data      # Garmin Nuvi 255W GPS의 속도에 대한 의견
    ├── speed_windows7.txt.data                  # Windows 7의 속도에 대한 의견
    ├── staff_bestwestern_hotel_sfo.txt.data     # Best Western Hotel (San Francisco)의 직원 서비스에 대한 의견
    ├── staff_swissotel_chicago.txt.data         # Swissotel (Chicago)의 직원 서비스에 대한 의견
    ├── transmission_toyota_camry_2007.txt.data  # 2007년형 Toyota Camry의 변속기에 대한 의견
    ├── updates_garmin_nuvi_255W_gps.txt.data    # Garmin Nuvi 255W GPS의 업데이트에 대한 의견
    ├── video_ipod_nano_8gb.txt.data             # iPod Nano 8GB의 비디오 성능에 대한 의견
    └── voice_garmin_nuvi_255W_gps.txt.data      # Garmin Nuvi 255W GPS의 음성 안내 성능에 대한 의견

In [25]:
import numpy as np
import pandas as pd
import os, glob     # 운영체제 경로 처리 / 파일 패턴 
path = "../data/OpinionsDataset1.0/topics"
all_files = glob.glob(os.path.join(path, '*.data'))

filename_list = []
opinions_list = []

for file_ in all_files:
    df = pd.read_table(
        file_,               # 경로
        header = None,       # 첫 줄은 컬럼명으로 사용안함
        index_col = None,    # 인덱스 컬럼 지정 안함(기본생성)
        encoding = "latin1"  # 특수문자 깨짐 방지
    )

    display(df)

    filename = os.path.basename(file_)     ## 파일명 추출
    filename = filename.split('.')[0]      # 확장자 제거
    filename_list.append(filename)         # 파일명 리스트 추가

    opinions = df.to_string(index = False, header = False) #인덱스/헤더 제거
    opinions_list.append(opinions)

                                                    0
0                      , and is very, very accurate .
1    but for the most part, we find that the Garmi...
2    This function is not accurate if you don't le...
3    It provides immediate alternatives if the rou...
4    I've used other GPS units, as well as GPS bui...
..                                                ...
62                      seems to be rather accurate .
63   It was accurate on determing original directi...
64                  Highly accurate, POIs are great .
65   I can't believe how accurate and detailed the...
66   Speed of calculation, accuracy, and simplicit...

[67 rows x 1 columns]

                                                    0
0    The room was not overly big, but clean and ve...
1    The second room was smaller, with a very inco...
2        Large comfortable room, wonderful bathroom .
3    The rooms were nice, very comfy bed and very ...
4          Bathroom was spacious too and very clean .
..                                                ...
83   Our suite we had was small there was pubic ha...
84              bathroom a little on the older side .
85            The bathroom needed a face, lift also .
86   The bathrooms are quite small compared to oth...
87   The hotel was of a good standard, big clean r...

[88 rows x 1 columns]

                                                    0
0    After I plugged it in to my USB hub on my com...
1    After you have paged tru a 500, page book one...
2    NO USER REPLACEABLE BATTERY, , Unless you buy...
3    After 1 year you pay $80 plus shipping to sen...
4   The fact that Kindle 2 has no SD card capabili...
..                                                ...
85  It came with battery uncharged, but it charged...
86             And the long battery life is amazing !
87                   The battery life seems amazing .
88   While the Kindle 2 shows the title on the lef...
89   By the way, Kindle battery lasts forever inde...

[90 rows x 1 columns]

                                                    0
0        short battery life  I moved up from an 8gb .
1      I love this ipod except for the battery life .
2                     long battery  scratch resistant
3             Battery drains even if I don't use it .
4    I only wonder why the battery seems to drain ...
..                                                ...
64       The video camera works great and the battery
65     Then you find the battery only lasts about 1 .
66   Long Battery Life, Sleek Compact, Easy To Set...
67  My only complaint with this product is that th...
68  I bought the nano as a replacement for an olde...

[69 rows x 1 columns]

                                                     0
0    6GHz 533FSB cpu, glossy display, 3, Cell 23Wh ...
1     Not to mention that as of now Asus will not s...
2     It also features a N270 cpu, 6, cell 48Wh Li,...
3    3MP webcam, 6, Cell 63Wh Li, ion Battery with ...
4            Realistic battery numbers are between 8 .
..                                                 ...
328  0 out of 5 stars Good ergonomics, exceptional ...
329   Pretty standard list of specs for a netbook w...
330                 The long battery life is awesome !
331   The battery is INFINITELY better, and I can e...
332   When I learned about the battery life, the me...

[333 rows x 1 columns]

                                                     0
0    I thought it would be fitting to christen my K...
1     As soon as I'd clicked the button to confirm ...
2    After reading through the introductory guide t...
3     I started reading with the default size witho...
4     The gadget feeling is underlined by needing t...
..                                                 ...
160   I love the  next page  button on both sides o...
161   The buttons on the K2 are not easily pressed ...
162   I flicked the switch to start reading, and th...
163  There is no 1, 800 number for Canada for Kindl...
164   I hit the button, bent over to plug in the Ki...

[165 rows x 1 columns]

                                                     0
0     Drivers seat not comfortable, the car itself ...
1     It's very comfortable, remarkably large insid...
2                 Front seats are very uncomfortable .
3     I'm 6' tall, and find the driving position pr...
4     However, there are a couple of things that ki...
..                                                 ...
161   Very comfortable drive, holds the road very n...
162   The Accord is so large, comforting, and easy ...
163   I was slightly concerned about all the review...
164   This is by far the most comfortable vehicle I...
165  When I bought this car a year ago, I initially...

[166 rows x 1 columns]

                                                     0
0     Ride seems comfortable and gas mileage fairly...
1     Seats are fine, in fact of all the smaller se...
2     Great gas mileage and comfortable on long tri...
3     Good gas mileage, comfortable seating, lots o...
4                      Lots of comfort for the price .
..                                                 ...
114   This new Camry is indeed very comfortable wit...
115   Very uncomfortable when driving long distances .
116   I am not real fond of the electric seat and I...
117   This car is easy to drive, great gas mileage ...
118   However, when we drove the Camry we were impr...

[119 rows x 1 columns]

                                                    0
0    You also get upscale features like spoken dir...
1    I used to hesitate to go out of my directions...
2    the directions didn't tell me anything I didn...
3    It also does not offer an option to view the ...
4    It gives your heading not in terms of degres ...
..                                                ...
94   It was accurate on determing original directi...
95   But driving on the highway with music on and ...
96   I didnt know the address of the mueseum so I ...
97  The display is very easy to read, and the dire...
98   The model 255W that we received seemed to tak...

[99 rows x 1 columns]

                                                    0
0            3 quot  widescreen display was a bonus .
1    This made for smoother graphics on the 255w o...
2    I also found that the display on the 255w was...
3    The 750 just displays text on the top line fo...
4    The 255 also automatically adjusts the font s...
5   Another feature on the 255w is a display of th...
6   The 255W has a really clear display that's eas...
7    The new display posts speed limit signs of ma...
8    The widescreen display makes it possible to v...
9   The bad ,  My unit only displays elevation con...
10  UPDATE ON THIS ,  It finally turned out that t...
11   I also miss the display of how far you have y...
12   My old unit counts this down for you and prov...
13   I have to hit too many buttons to get back to...
14   Display is excellent ,  the layout of informa...
15   In the map view, if you touch the display but...
16   The navigation display shows more information...
17   For me, the visual display combined with this...
18  So I finally got the Nuvi 255w after months of...
19     It also can display and speak many languages .
20   I am thinking about buying another one of the...
21          The display is great, and is very clear .
22   The instructions sometimes are a little diffi...
23   The way map is displayed is good and the wide...
24   Through this option you can find sub, options...
25   The extra features of the 255W over lesser mo...
26   Since the directions are also displayed on th...
27   I have checked the display in three areas I a...
28   But is impossible to display them and your cu...
29   Even setting the display to maximum detail is...
30   I have really sensitive eyes and sometimes th...
31  The display is extremely legible both in brigh...
32   I used it the day I bought it,   and then thi...
33  ,  The speed limit sign on the display is hand...
34  The unit speaks street names, has a beautiful ...
35   Also, if you're searching for a business, it ...
36   I also like the way the display changes backg...
37   I thought I had seen a turn by turn display b...
38   Well when I saw that the 255W had the next tu...
39                 The Garmin has a nice 3d display .
40  One unexpected feature is the speed limit and ...
41   I like the larger display and quicker updatin...
42   I really like the versatility of picking dest...
43         The display is bright & clear in the car .
44      The display is laid out better than the 660 .
45   It is very easy to use, and when driving in t...
46  it should have the names of streets written do...
47  The display is very easy to read, and the dire...
48   The new speed limit display on the 205 255 is...
49   The sound went out on it and only the display...

                                                    0
0    It feels as easy to read as the K1 but doesn'...
1    the white is really GREY, and to avoid consid...
2    The dream has always been a portable electron...
3     they would ask, to which I would squint my e...
4    I found that the Kindle 2 is immediately appe...
..                                                ...
75   The print is easy on the eye and the light we...
76   The Text, to, Speech function is great for ti...
77   I have an  eye issue  and noticed it was gett...
78   I enjoy having the text at the largest size b...
79          The e ink is so comfortable on the eyes .

[80 rows x 1 columns]

                                                    0
0    I had to uninstall anti, virus and selected o...
1    This review briefly touches upon some of the ...
2    All of these features combine to create a muc...
3   I enjoyed the new convenience features in Wind...
4    They showed me PC laptops that had more featu...
..                                                ...
57             Smooth OS with great little features .
58   A lot of the new finder desktop windows featu...
59   If you didn't come over from the bright side ...
60   I am not going to review the features, becaus...
61  There is not a lot of new features in the oper...

[62 rows x 1 columns]

                                                    0
0    Being able to change the font sizes is awesome !
1    For whatever reason, Amazon decided to make t...
2    I found myself constantly changing the angle ...
3    I was an avid reader but increasing age has m...
4        What's more, it's easy to change font size .
..                                                ...
59   I am in my 50's and the reading vision isn't ...
60   The interface is a bit like reading newsprint...
61   It is so much easier to read than a paper pag...
62  it's just like reading a paper book, but BETTE...
63  font sizes and page orientation can be adapted...

[64 rows x 1 columns]

                                                     0
0     The room was packed to capacity with queues a...
1     The over zealous   staff cleared our unfinish...
2     There are a couple pubs, a great patisserie a...
3    The neighborhood is an upscale residential are...
4    The food   was wonderful, a selection of sandw...
..                                                 ...
106   Really good Indian food is just a few blocks ...
107  There is an Internet cafe, laundramat and Sain...
108   It is in a nice neighborhood with fast food, ...
109   because it has sensor to count how many times...
110   The food was delicious in both the Consortia ...

[111 rows x 1 columns]

                                                    0
0              The food for our event was delicious .
1    The food in the lounge was great and very fre...
2    As far as food, walk a few blocks toward Mich...
3    The Palm resturant in the hotel had some spec...
4    Took the charge of the minibar which we had u...
5    We never ate anything onsite so I can't vouch...
6    The Lobby bar does not serve food very late a...
7    In any case, I had allotted approximately $15...
8    But the presentation was awesome and the food...
9    The food was delicious and the view was fabul...
10   For self catering types, Bockwinkels is a wel...
11   Room service was extortionate though, very ve...
12   We also did the chicago food tasting tour whi...
13   So if you move around bottles in the fridge s...
14   We passed on the restaurants simply because t...
15   Also don't forget to go the &quot The River N...
16   An added bonus was the Executive Lounge with ...
17   Room service food quality was very good but w...
18   there is a market one block south of the Hyat...
19   Had an appetizer at the Lobby Lounge, and the...
20               The hotel buffet had fabulous food .
21   I didn't dine in the hotel, so I can't tell y...
22   We enjoyed the breakfast although the other e...
23   Room service got my breakfast order wrong but...
24   I was delighted as the waiters were very frie...
25   mile with traditional Italian food and a grea...
26   A nice restaurant with reasonable prices and ...
27            Good but pricey food, great breakfast .
28   My only complaint is the Palm restaurant, it ...
29   If you want good food at a decent price, ther...
30   We ordered room service for late night ice cr...
31  Ed Debevics is fun, , sassy servers, diner foo...
32  Brain Food Cafe in the museum of Science and I...
33   No line, a plate full of REAL food with drink...
34   Staying with food, try also the Weber Grill, N .
35  The few complaints I had were as follows ,  re...
36                  But the food was good and fresh .
37   Very friendly servers and nice selection of f...
38   We called several times and within 30 minutes...
39                      The Italian food was superb .
40   My wife and I are food snobs, and this place ...
41   Very much enjoyed the Chicago Food Tour, a wa...
42   Room service was efficient, average priced, a...
43   I ate their last night and the food and servi...
44  I had a great experience here from the quality...
45   The hotel is advertised to have multiple rest...
46   There's an escalator that goes into the basem...
47  , followed shortly thereafter by a knock and a...
48   Food unexceptional although the breakfast buf...
49   We were able to get a crib, a play pen, and a...
50   The food at the Swissotel is better than the ...

                                                     0
0    The wine reception is a great idea as it is ni...
1     They also have a computer available with free...
2     The service was good, very friendly staff and...
3     has free wireless and help you with transport...
4     The nightly free wine tasting from 5 ,  6 pm ...
..                                                 ...
119   Parking was $26 day ,  free valet with on and...
120   The hotel was of a good standard, big clean r...
121   The staff are friendly and there is one compu...
122   During that time there is a very nice and kno...
123   It's location is fantastic if you want to get...

[124 rows x 1 columns]

                                                     0
0     Ride seems comfortable and gas mileage fairly...
1                        It gets great gas mileage   .
2     Being a mother who drives a lot I wanted a sa...
3     Great gas mileage and comfortable on long tri...
4              Nice looking car and good gas mileage .
..                                                 ...
110          Mileage is mediocre at an average of 25 .
111   The 4 cylinder does not get good mileage at 7...
112   Below it you can expect to get good mileage o...
113   This car is easy to drive, great gas mileage ...
114   Doesn't anyone build a quiet car out there fo...

[115 rows x 1 columns]

                                                    0
0    I love the new body style and the interior is...
1    However, there are a couple of things that ki...
2    Love the interior and the power and speed, bu...
3    Love the interior and exterior look, the V6 i...
4    The seats are decent, the interior design is ...
..                                                ...
89   Tonight I find that my headlights, brake ligh...
90     Interior is good but has quite a few rattles .
91   I am a bit disappointed with the interior pla...
92   At highway speeds, the interior remains quiet...
93   However I have few complaints about the inter...

[94 rows x 1 columns]

                                                     0
0     First of all, the interior has way too many c...
1     3 blown struts at 30,000 miles, interior trim...
2           Insanely cheap plastic all over interior .
3      Disappointed in interior and exterior quality .
4     I love the color of the exterior and interior...
..                                                 ...
104    Second, the interior designer should be fired .
105   It is surprising how spacious the interior is...
106       The plastic interior looks and feels cheap .
107   The interior is okay and I have not had any r...
108   The interior rattles, with pieces falling off...

[109 rows x 1 columns]

                                                     0
0    ,  I think the new keyboard rivals the great h...
1    Since the battery life difference is minimum, ...
2     The keyboard is now as good as the HP and Sam...
3     The keyboards are 92% the size of those found...
4     The keyboard is large enough to accommodate t...
..                                                 ...
121  The keyboard is awesome since it looks like re...
122   I like the zoom in out feature on the keyboard !
123   The keyboard is only slightly smaller than a ...
124   I mostly find that when I make typos, it's no...
125  A lot of netbooks on the market have mangled t...

[126 rows x 1 columns]

                                                     0
0           Good Value good location ,  ideal choice .
1    Great Location ,  Nice   Rooms ,  Helpless Con...
2     The location is good, and the overall decor i...
3     Overall, it was a good location, but an avera...
4    A perfect hotel a perfect location perfect sta...
..                                                 ...
326                   Great Place Even better location
327   It was a very convenient location to Pier 39 ...
328        Value location and  they remember your name
329   It's location is fantastic if you want to get...
330               Decent suite OK price great location

[331 rows x 1 columns]

                                                     0
0     Great location for tube and we crammed in a f...
1    All in all, a normal chain hotel on a nice loc...
2                      Great Price Terrific Location .
3               The location is absolutely wonderful .
4    Our main focus before booking was looking for ...
..                                                 ...
407   This is definitely a modern hotel, no English...
408   The location could not be better and best of ...
409   Everything worked well, was in good condition...
410   Service was great and the location of the hot...
411     Great room fabulous price wonderful location !

[412 rows x 1 columns]

                                                     0
0     It's quiet, get good gas mileage and looks cl...
1     The mileage is great, and I've had to get use...
2                Thought gas mileage would be better .
3    There are trade offs that I have no problems w...
4     I chose it for the low emissions, value for t...
..                                                 ...
159                     Gas mileage is above average .
160   Great power, great ride, and pretty good fuel...
161   Gas mileage is at it's highest 24 mpg usually...
162   The VCM definitely helps the mileage ,  it wa...
163   Little 4cyl 5 spd LX and it got awesome gas m...

[164 rows x 1 columns]

                                                    0
0    In fact, the entire navigation structure has ...
1                  Navigation is a huge improvement .
2    Clearly, Amazon was hard at work to make navi...
3    I tried out the free 14 day trial on newspape...
4    Once I got used to it, the navigation was eas...
..                                                ...
58   I really enjoy the menu button and the 5, way...
59  I found the screen readability and overall use...
60  I found the Kindle Store to be full featured a...
61   The buttons on the K2 are not easily pressed ...
62  I was worried about navigation without the scr...

[63 rows x 1 columns]

                                                    0
0    Parking was expensive but I think this is com...
1    there is a fee for parking but well worth it ...
2    The parking was free, which was great, and th...
3   As for in, and, out parking, I have seen a lot...
4    They have a parking garage, but they make you...
..                                                ...
92   I was aupset, since my $89 night room had gon...
93   We didn't pull our car out of the parking gar...
94        Parking is not cheap, check before you go .
95               Parking was only $10 with AAA rate .
96               Hotel parking   is now $23 a night .

[97 rows x 1 columns]

                                                    0
0   Very happy with my 08 Accord, performance is q...
1    6, 4, 3 eco engine has poor performance and g...
2    Overall performance is good but comfort level...
3    I'm impressed with the performance as well as...
4    It has room, performance, good MPG for its si...
5    For the record I test, drove the Lexus350 the...
6    Very happy with the car enjoy the ride and pe...
7      The performance of the engine is very smooth .
8    This car had rattles at 500 miles and has hor...
9    Great performance and handling make this a re...
10   Engine performance lacks punch after 60, head...
11   There seem to be so many components that ente...
12  Features, quality, reliability, and performanc...
13   190 HP engine is a good compromise for perfor...
14  I owned this car for only a week, but I am ple...
15  This car lacks the performance and handling of...
16   Good looking inside and out, comfortable and ...
17   Still enjoy interior and exterior styling as ...
18   I just put it on the highway this weekend and...
19   The bigger size has taken some getting used t...
20   It fits right , is fun to drive, great stereo...
21   If you want sports sedan handling and perform...
22   I went for comfort over performance to fit it...
23   I researched many other makes and models but ...
24   Performance is outstanding, more like a sport...
25   Lots of power with the 6 spd, and the car has...
26        No problem with quality, performance, etc .
27               Engine performance is very lacking .
28  t anywhere close to 3 series on many facets, n...
29   The 4 cylinder lacks performance and handling...
30   The car is great, both with styling and perfo...
31   I purchased a 2004 V6,  Leather and I did not...
32   I love the styling the performance and handli...
33  I was looking for a luxury, feel car with grea...
34  Overweight ,  3600 pounds, lots of road noise,...
35   The interior design and the performance of th...
36  I was looking for a mid size coupe with style,...
37  Styling in and out is fantastic, and the v, 6 ...
38   It does not diminish the performance of the c...
39  After tracking almost 2 months of research on ...
40   My my, I have never experienced such smooth p...
41   I admire engine performance and comfort while...
42  I have owned 4 honda's and have come to rely o...
43   The car is superb, performance, styling, qual...
44                    The performance is incredible !
45   Gas mileage is great for a vehicle with this ...
46   I could not be happier with the performance a...
47   When I first tested the EX, L V6, the perform...
48   Honda has outdone itself on styling and perfo...
49   Its ride, comfort and overall performance is ...
50   The previous models were boring both aestical...

                                                    0
0    The Eee Super Hybrid Engine utility lets user...
1    In Super Performance mode CPU, Z shows the bu...
2   One word of advice is to be really careful abo...
3    Whatever you elect to install I would highly ...
4    I expect to get 6, 7 hours in high performanc...
5    faster overall performance, and shorter charg...
6    Asus' center of excellance is in very reliabl...
7    I have the Super Hybrid Engine set to auto mo...
8    Comes with unusually well, written documentat...
9    Overall though, I am happy with the performan...
10  4 PASS ,  Battery life is amazing, used the la...
11  As for the performance of this little computer...
12   The performance is great for it's size ,  rem...
13   Just some advice ,  use Eset's anti, virus an...
14   Upgrade to 2gb of memory, but did not seem to...
15   I find that the performance is great for my u...
16   I keep a couple of apps running and its perfo...
17  Amazon seems to be concerned that I am simply ...
18   The reviews on many of the higher resolutions...
19   I haven't hit my swap yet in several weeks of...
20   Replacing them isn't very hard given a screw ...
21   Otherwise its performance has been bug, free ...
22   It enhances performance, but is not absolutel...
23                The Wireless performance is great .
24  0 out of 5 stars Excellent balance of performa...
25  I am very satisfied with the performance of th...
26   This did not affect me much, I can write with...
27  The small size makes it very easy to carry com...
28   The only area that I've seen, so far, where t...
29  0 out of 5 stars Excellant Portability and Per...
30  I'm actually downgrading in performance in get...
31   I then loaded Windows 7 RC and the performanc...
32   After upgrading to 2Gb of memory   and deleti...
33   I have the following software installed and t...
34                No noticeable performance reduction
35   Performance reduction here is much less than ...
36  My desktop is a very strong dual, core compute...
37   1 light weight, 2 long battery life, and 3 re...
38   Performance is good, screen very good, wirele...
39   Battery performance couldn't be more nice, as...
40  Been very pleased with performance and battery...
41  The performance is fantastic ,  opening a brow...
42   I had thought the RAM was too small for good ...
43   I spent a bit of time researching the various...
44   The performance and speed of this laptop is a...
45  I was aprehensive about its capabilities while...
46   I use this setting but it shouldn't be used f...
47   There's only 1 GB of RAM, and that's good eno...
48   It freaked me out since I wasn't running anyt...
49  0 out of 5 stars Good ergonomics, exceptional ...
50   Very acceptable performance for what netbooks...

                                                    0
0    If a case was included, as with the Kindle 1,...
1      lower overall price, with nice leather cover .
2   If you have the first Kindle and are deciding ...
3    Before purchasing, I was obsessed with the re...
4    However, I think all the positives of the K2 ...
..                                                ...
95   to buy the international version of the kindl...
96  no waiting time for the paperback version, and...
97            4 Delivery and Prices for Austrian User
98  The average price of an up, to, date e, book f...
99   Non, best seller book prices should be lower,...

[100 rows x 1 columns]

                                                     0
0    All in all, a normal chain hotel on a nice loc...
1                      Great Price Terrific Location .
2    Our main focus before booking was looking for ...
3     All for the bargain price off £ 250 for 2 nig...
4    Explore the area and you will find plenty of p...
..                                                 ...
138   We had terrific price per room and seems hard...
139   There is a great supermarket and some restaur...
140   This is definitely a modern hotel, no English...
141  After initial angst of getting a room, after a...
142     Great room fabulous price wonderful location !

[143 rows x 1 columns]

                                                    0
0    I previously owned a Toyota 4Runner which had...
1   I bought the Camry because of Toyota reliabili...
2   I purchased a 2007 Camry because of the looks ...
3    As of today, I am a bit disappointed in the b...
4     Disappointed in interior and exterior quality .
..                                                ...
67   My transmission works seamlessly and there ar...
68   I was driving 91 Camry for long time and it's...
69   While I love the design, the poor components,...
70   I love the car's visual and aesthetic design,...
71  I had always heard that Toyota had the best qu...

[72 rows x 1 columns]

                                                     0
0    Great Location ,  Nice   Rooms ,  Helpless Con...
1     The rooms were bright, clean and the windows ...
2     Another odd thing we noticed is a majority of...
3     The rooms are on the small side but they're s...
4                  The rooms were spacious and clean .
..                                                 ...
261   And value is key for the rooms and the service !
262   The rooms are sometimes small, but when you'r...
263   The service is always great and the rooms ver...
264   Am sorry for those few noisey rooms that some...
265   The rooms are very clean and very well appoin...

[266 rows x 1 columns]

                                                     0
0    The Swissotel is one of our favorite hotels in...
1     The rooms look like they were just remodled a...
2    Great rooms staff and location but extras over...
3      Hotel was very clean and the rooms were comfy .
4     the standard rooms are small, the lobby bar i...
..                                                 ...
151   The rooms were clean and big and the view of ...
152                Expensive Parking but great rooms .
153                      Rooms were nicely furnished .
154   Pool is nice with whirlpool and saunas in the...
155   The rooms are business, oriented, so they are...

[156 rows x 1 columns]

                                                     0
0    We arrived at 23,30 hours and they could not r...
1     We had a room with two double beds which was ...
2    The room was quiet, clean, the bed and pillows...
3             We arrived about 11 am, room was ready .
4     Room was good size for Europe ,  clean throug...
..                                                 ...
570        The room was thoroughly cleaned every day .
571   When I arrived in my room with two small chil...
572   Also when we booked the hotel we were told we...
573   The room was very comfortable although the cu...
574   Be cautious of using the room services like t...

[575 rows x 1 columns]

                                                    0
0                   It's fast to acquire satellites .
1    If you've ever had a  Brand X  GPS take you o...
2    The Garmin Nuvi 255W connects to satellites e...
3   It picks up the satellites quickly  , routes f...
4    The revised chipset allows the GPS to make sa...
..                                                ...
58   Took a few minutes for the unit to link up wi...
59   Also, as a novice user, I am really surprised...
60   My only complaints so far is that the gps los...
61   It's fast in aquiring satellites and fast in ...
62   It grabs satellites quickly and recalculates ...

[63 rows x 1 columns]

                                                     0
0      It is easy to read and when touching the scr...
1     and zoom out   buttons on the 255w to the sam...
2     On the 750 the zoom buttons are on opposite s...
3     The screen is easily readable in the sun, and...
4     Display is excellent ,  the layout of informa...
..                                                 ...
99   It speaks the street names if you touch the ca...
100   Screen size is good and I didn't want one tha...
101   With either unit, the text on the screen usua...
102   I've only used the wide screen versions, so I...
103  The Garmin nuvi 255W I bought through Amazon h...

[104 rows x 1 columns]

                                                    0
0    As always, the video screen is sharp and brig...
1   2, inch screen   and a glossy, polished alumin...
2    Still, video fans should consider stepping up...
3   2, inch screen can now display up to 12 lines ...
4    Apple's iconic Click Wheel navigation can sti...
5    It looks great, is easy to handle, the screen...
6    And the 5th generation has a larger screen si...
7    I've owned all the iPod Nanos at one point an...
8    However, it doesn't have the touch screen cap...
9    It's really amazing just how big the screen i...
10   The picture on the small screen is surprising...
11  5G lies a more mature iPod, many steps wiser a...
12   New features like lager screen and radio is a...
13                 The screen and built in speaker  .
14   The screen is easy to read and the built in s...
15                The larger screen is a great plus .
16   Don't waste your money on those 200 dollar it...
17  video, motion sensing, screen size and sllek l...
18   Easy to use  This new iPod is easy to use, ha...
19   Good features, small and light weight but a b...
20   The video camera is great and the screen size...
21   does do much in a very tiny space, bigger scr...
22   there are alot of new features in this model ...
23   Screen scratches easily  Wanted an IPOD to li...
24                 has bigger screen, video camera  .
25   what i also like is that it has a bigger scre...
26   I found a lovely cheapo case with screen prot...
27       the screen is bigger so i can watch movies .
28   i love the camra, and the larger screen, and ...
29   good screen quality  Bought as a bday gift an...
30   i couldnt think of a single thing  this ipod ...
31   slim, size, vedio camera, screen clarity, pho...
32   What's more, even if I cut a long essay into ...
33   Price, Size, Screen, FM Radio, Camera, Capaci...
34      The battery is great and the screen as well .
35             The larger screen is a plus for sure .
36                     Screen resolution is awesome .
37   Lack of a belt clip accessory that also prote...
38   The only negative thing I would say is that I...
39   Easy to use video camera, Big screen, Fun col...
40   Also the screen I love how big it and, how ea...
41   Screen does not scratch, but can get fingerpr...
42   Very easy to use, love the pedometer, lightwe...
43  but I'm really disappointed they didn't keep t...
44   Nice size screen, good speakers for size, gre...
45   Video is impressive, speaker sound is good fo...
46   Watched one last night in bed while mrs was s...
47   The old Nano stuff fits but no openings for c...
48                      New Features, Bigger Screen .
49   Now all it needs is a camera that can take st...
50   Small size and Color, Gettin your Money's wor...
51   Same as last model with some differences in s...
52   The mic and camera are great, speaker is grea...
53   If these get much smaller, though, I won't be...
54   It's small and lightweight, it looks amazing,...
55   I like the fm radio, have an audio book and e...
56  I bought the nano as a replacement for an olde...
57  This is a vast improvement on the last Nano, w...

                                                     0
0     Keep in mind that once you get in a room full...
1     I've used mine outside on a sunny day, and th...
2     In fact it was much more detailed than the ma...
3     Some ppl may prefer a higher resolution scree...
4     I delayed ordering the computer because of th...
..                                                 ...
173   And maybe it's something I need to figure out...
174   Has all the features of my bigger laptop exce...
175               1 inch screen is bigger than the 8 .
176   I want a netbook for portability, not screen ...
177  , I was willing to downsize my screen size in ...

[178 rows x 1 columns]

                                                    0
0                Front seats are very uncomfortable .
1    No memory seats, no trip computer, can only d...
2           needs power seats on the passenger side .
3    I haven't had any back pain from the seats, m...
4    There is a great deal of road noise in the ca...
..                                                ...
76   We are both tall, 5'11'' and 6'2  and have no...
77   After driving it for a few months I found the...
78   Seats are too firm and leather is quite  hard...
79   I was slightly concerned about all the review...
80            I love the seats, they are supportive .

[81 rows x 1 columns]

                                                     0
0     Both of us having worked in tourism for over ...
1     The service was good, very friendly staff and...
2     Also, thanks to Ken the concierge for recomme...
3     The restaurant is not cheap but is very well ...
4     Service was spotty  Front desk was marginally...
..                                                 ...
139   Being that I worked as a front desk person at...
140   We asked her how to get back to the airport w...
141   And value is key for the rooms and the service !
142   The service is always great and the rooms ver...
143       nette Lage aber durchschnittlicher Service !

[144 rows x 1 columns]

                                                     0
0    not customer, oriented hotelvery low service l...
1    The room was quiet, clean, the bed and pillows...
2     There were no service issues to speak of, but...
3    Good Location Horrible Service Disgusting Proc...
4    If you're looking for a full, service experien...
..                                                 ...
165  , We booked our room through an internet servi...
166   We also love the service of the staff, not to...
167  I was very disappointed with the service from ...
168   Service was great and the location of the hot...
169   Be cautious of using the room services like t...

[170 rows x 1 columns]

                                                     0
0     Mediocre room and service for a very extravag...
1     The accomodations and support services are ph...
2     no robes in the rooms, ice machines are not o...
3    Concierge service was fine when we needed our ...
4            Room service was expensive in the hotel .
..                                                 ...
193   I cannot comment on room services, however th...
194                    Exceptional rooms and service !
195   Service was excellent and the suites were lar...
196      Beautiful Hotel ,  Service Slightly Lacking .
197   Great service in there, and a nice quiet plac...

[198 rows x 1 columns]

                                                    0
0    A few other things I'd like to point out is t...
1    The full size right shift key was enough for ...
2    You should understand that this is not a full...
3    The keyboards are 92% the size of those found...
4    The keyboard has a responsive feel and the la...
..                                                ...
81   His full sized laptop dies after about 2 hour...
82   The keyboard is nearly full size and very com...
83  9 I was used to, the increase in size and or w...
84   Other than that, it is an amazing little comp...
85  , I was willing to downsize my screen size in ...

[86 rows x 1 columns]

                                                     0
0     headphone jack i got a clear case for it and ...
1     Picture and sound quality are excellent for t...
2     Great sound, easy to load & use once I read t...
3          The music I loaded sounds clear and crisp .
4     As for the overall sound I would give it a 8 ...
..                                                 ...
96    I don't particularly use it with headphones a...
97        No way to balance sound between ear pieces .
98    Sound in one side is significantly higher tha...
99    I have used the video camera nd the sound is ...
100          Good sound and useful as a radio but that

[101 rows x 1 columns]

                                                    0
0   Another feature on the 255w is a display of th...
1    I found myself not even looking at my car spe...
2   My final decision was to keep the 255w and ret...
3    It even tells you the speed limit on most roa...
4    The new display posts speed limit signs of ma...
..                                                ...
64  Plus you can download speed cameras alerts at ...
65   I can't believe how accurate and detailed the...
66   What I like most about the 255W is that it sh...
67   The new speed limit display on the 205 255 is...
68   Speed of calculation, accuracy, and simplicit...

[69 rows x 1 columns]

                                                     0
0    Windows 7 is quite simply faster, more stable,...
1    , faster about 20% to 30% faster at running ap...
2     Yes, it'll make your computer run a bit slowe...
3                      ,  Fast startup and performance
4     Also, in my non, benchmarked experience, Wind...
..                                                 ...
119  0 out of 5 stars Windows 7 runs slower than Vi...
120  Since putting Windows 7 on my computer, the co...
121  So I just got the Windows 7 upgrade installed ...
122  Simply put, Windows 7 looks amazing, and is fa...
123   I started to upload a youtube video, went awa...

[124 rows x 1 columns]

                                                     0
0                   Staff are friendly and helpful   .
1     The staff in the morning seemed to need anoth...
2    A perfect hotel a perfect location perfect sta...
3     The front desk staff is more than eager to he...
4     The staff is friendly and we only went to one...
..                                                 ...
313                  Staff were friendly and helpful .
314      The front desk staff were more than helpful .
315   The staff was very aggressive about checking ...
316   The staff is wonderful to deal with and very ...
317                 Wonderful Hotel ,  Excellent Staff

[318 rows x 1 columns]

                                                     0
0     The staff at Swissotel were not particularly ...
1     Each time I waited at the counter for staff  ...
2     All staff members are very courteous and go t...
3     The staff was great and put us on the 30th fl...
4     The staff is friendly and knowledgeable about...
..                                                 ...
199   They treated us like royalty, the staff assis...
200   Everything there was in great shape, and all ...
201   The staff at the front desk and the concierge...
202          Very nice hotel with well trained staff .
203   The staff was courteous, professional and eff...

[204 rows x 1 columns]

                                                     0
0     After slowing down, transmission has to be  k...
1     I wonder if the people who have problems with...
2     The transmission, I don't know what to tell y...
3    I did not notice any hesitation with the trans...
4     I've had the same transmission problems hesit...
..                                                 ...
150   The transmission is the absolute WORST, it is...
151          They have finally fixed my transmission .
152   Only problem has been the proprietary transmi...
153   I have 4 cyl with manual transmission ,  lack...
154   Transmission big issue and also rattles more ...

[155 rows x 1 columns]

                                                    0
0   Another thing to consider was that I paid $50 ...
1    update and reroute much _more_ quickly than m...
2   UPDATE ON THIS ,  It finally turned out that t...
3    it's a curiousity for most of us, traffic and...
4   The text to speech is great for not having to ...
..                                                ...
61   Loading a map update is another experience I ...
62   Haven't driven with it yet since the update b...
63              Glad I updated the map and software .
64   Since the update , Drove it locally in San Di...
65   in a  test  the day I received the unit, befo...

[66 rows x 1 columns]

                                                     0
0    I bought the 8, gig Ipod Nano that has the bui...
1      Itunes has an on, line store, where you may ...
2    I have lots of music cd's and dvd's, so curren...
3    There's a right way and wrong way to store mus...
4     Audio and video recording are a step above th...
..                                                 ...
210   The video camera is crystal clear and the mem...
211  she was quickly able to download music and vid...
212   I have used the video camera nd the sound is ...
213   FM radio and a   video camera are pretty darn...
214                    Great little audio video device

[215 rows x 1 columns]

                                                    0
0     The voice prompts and maps are wonderful esp...
1   I also thought the the voice prompts of the 75...
2    The 750 sounds more like a real female voice,...
3    I didn't have the problems with the sounds of...
4                   Some of the voices are annoying .
..                                                ...
84  Others have said that the voice directions lea...
85   I must say, though, that I believed it would ...
86      The voice commands are excellent and timely .
87   The model 255W that we received seemed to tak...
88   The voice is very clear and gives plenty of w...

[89 rows x 1 columns]

In [26]:
document_df = pd.DataFrame({
    'filename': filename_list,
    'opinions': opinions_list
})

document_df

,filename,opinions
0,accuracy_garmin_nuvi_255W_gps,...
1,bathroom_bestwestern_hotel_sfo,...
2,battery-life_amazon_kindle,...
3,battery-life_ipod_nano_8gb,...
4,battery-life_netbook_1005ha,...
5,buttons_amazon_kindle,...
6,comfort_honda_accord_2008,...
7,comfort_toyota_camry_2007,...
8,directions_garmin_nuvi_255W_gps,...
9,display_garmin_nuvi_255W_gps,...
10,eyesight-issues_amazon_kindle,...
11,features_windows7,...
12,fonts_amazon_kindle,...
13,food_holiday_inn_london,...
14,food_swissotel_chicago,...
15,free_bestwestern_hotel_sfo,...
16,gas_mileage_toyota_camry_2007,...
17,interior_honda_accord_2008,...
18,interior_toyota_camry_2007,...
19,keyboard_netbook_1005ha,...
20,location_bestwestern_hotel_sfo,...
21,location_holiday_inn_london,...
22,mileage_honda_accord_2008,...
23,navigation_amazon_kindle,...
24,parking_bestwestern_hotel_sfo,...
25,performance_honda_accord_2008,...
26,performance_netbook_1005ha,...
27,price_amazon_kindle,...
28,price_holiday_inn_london,...
29,quality_toyota_camry_2007,...
30,rooms_bestwestern_hotel_sfo,...
31,rooms_swissotel_chicago,...
32,room_holiday_inn_london,...
33,satellite_garmin_nuvi_255W_gps,...
34,screen_garmin_nuvi_255W_gps,...
35,screen_ipod_nano_8gb,...
36,screen_netbook_1005ha,...
37,seats_honda_accord_2008,...
38,service_bestwestern_hotel_sfo,...
39,service_holiday_inn_london,...
40,service_swissotel_hotel_chicago,...
41,size_asus_netbook_1005ha,...
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it and ...
43,speed_garmin_nuvi_255W_gps,...
44,speed_windows7,...
45,staff_bestwestern_hotel_sfo,...
46,staff_swissotel_chicago,...
47,transmission_toyota_camry_2007,...
48,updates_garmin_nuvi_255W_gps,...
49,video_ipod_nano_8gb,...
50,voice_garmin_nuvi_255W_gps,...

In [27]:
import nltk

nltk.download('wordnet') # 대형 의미 사전

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SJ\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [28]:
from nltk.stem import WordNetLemmatizer  # 표제어(lemma) 추출 도구

lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('running', pos = 'v')) # 동사로 간주해 표제어(사전 대표 기본형) 변환
print(lemmatizer.lemmatize('ran', pos = 'v'))

run
run

In [29]:
# 파이썬에서 사용하는 문장부호 목록
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
# 텍스트를 정리하고 표제어(동사 기준)으로 반환하는 함수
def lemmatize(text):
    text = text.lower() # 소문자 변환

    punc_rem_dict = dict((ord(ch), None) for ch in string.punctuation) # 문장부호 제거용 치환 딕셔너리
    print(punc_rem_dict)
    text = text.translate(punc_rem_dict)  # text에서 문장부호에 해당하는 것들은 None 매핑 -> 삭제처리

    tokens = nltk.word_tokenize(text)     # 단어 단위로 토큰화

    lemmatizer = WordNetLemmatizer()      # 표제어 추출 객체 생성
    return [lemmatizer.lemmatize(token, pos = 'v') for token in tokens]

lemmatize('The Matrix is everywhere its all around us, here even in this room. You can see it out your')

{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}

['the',
 'matrix',
 'be',
 'everywhere',
 'its',
 'all',
 'around',
 'us',
 'here',
 'even',
 'in',
 'this',
 'room',
 'you',
 'can',
 'see',
 'it',
 'out',
 'your']

In [ ]:
# Lemmatize 적용한 후 TF-IDF 벡터화
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    tokenizer = lemmatize,          # 사용자 정의 토크나이저 적용
    stop_words = 'english',         # 영어 불용어 제거
    ngram_range = (1,2),            # 유니그램, 바이그램
    max_df = 0.85,                  # 전체 문서 85% 초과 등장시 흔한 단어이므로 제외
    min_df = 0.05                   # 전체 문서 5% 미만 등장시 희귀한 단어이므로 제외
)

opinions_vecs = tfidf_vectorizer.fit_transform(document_df['opinions'])
print(opinions_vecs.toarray().shape) # (문서 수, 특성 수)
print(opinions_vecs)                 # 희소행렬 출력

c:\Users\SJ\NLP\nlp_venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\SJ\NLP\nlp_venv\Lib\site-packages\sklearn\feature_extraction\text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['make'] not in stop_words.
  warnings.warn(

{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}

In [35]:
tfidf_vectorizer.vocabulary_ # 단어 사전

{'accurate': 165,
 'garmin': 1463,
 'software': 3407,
 'provide': 2815,
 'directions': 1016,
 'intend': 1866,
 'function': 1444,
 'dont': 1053,
 'leave': 2031,
 'battery': 360,
 'mode': 2358,
 'say': 3165,
 'stop': 3550,
 'lunch': 2226,
 'play': 2686,
 'game': 1459,
 'immediate': 1799,
 'route': 3143,
 'online': 2540,
 'map': 2266,
 'program': 2803,
 'block': 443,
 'ive': 1910,
 'gps': 1532,
 'units': 3798,
 'build': 519,
 'cars': 594,
 'day': 928,
 'beat': 374,
 'accuracy': 164,
 'point': 2705,
 'b': 329,
 '100': 15,
 'everytime': 1206,
 'disappoint': 1025,
 '0': 0,
 '5': 101,
 'star': 3511,
 'honest': 1700,
 'review': 3012,
 'read': 2884,
 'aside': 280,
 'destination': 989,
 'throw': 3671,
 'close': 703,
 'fantastic': 1295,
 'feature': 1313,
 'plus': 2702,
 'hear': 1649,
 'pois': 2710,
 'pretty': 2749,
 'info': 1836,
 'amaze': 233,
 '1': 7,
 'state': 3519,
 'machine': 2230,
 'sign': 3320,
 'interstate': 1887,
 'highly': 1677,
 't': 3608,
 'depend': 970,
 'travel': 3737,
 'trip': 3745,
 'usually': 3853,
 'screen': 3173,
 'easy': 1121,
 'voice': 3906,
 'tell': 3630,
 'minute': 2346,
 'arrive': 276,
 'home': 1696,
 'navigator': 2407,
 'doesnt': 1046,
 'navigate': 2402,
 'straight': 3555,
 'road': 3038,
 'familiar': 1290,
 'streets': 3562,
 'nuvi': 2509,
 'arrival': 275,
 'estimate': 1194,
 'quite': 2860,
 '255w': 61,
 'rout': 3142,
 'generally': 1477,
 'discover': 1030,
 'errors': 1189,
 'internal': 1880,
 'line': 2093,
 'want': 3925,
 'unit': 3797,
 'reliable': 2963,
 'satellite': 3158,
 'connection': 819,
 'town': 3720,
 'extremely': 1266,
 'update': 3807,
 'garmins': 1465,
 'website': 3954,
 'golden': 1495,
 'lot': 2190,
 'friends': 1437,
 'address': 181,
 'load': 2110,
 'quickly': 2849,
 'recalculate': 2927,
 'miss': 2353,
 'turn': 3764,
 'street': 3559,
 'level': 2041,
 'able': 141,
 'guide': 1613,
 'exact': 1210,
 'location': 2118,
 'inside': 1856,
 'shop': 3307,
 'mall': 2256,
 'latest': 2018,
 'soon': 3414,
 'receive': 2928,
 'blow': 447,
 'away': 321,
 'capability': 567,
 'thing': 3658,
 'buy': 541,
 'morning': 2373,
 'come': 731,
 'ready': 2894,
 'downfall': 1070,
 'product': 2796,
 'reason': 2920,
 'fact': 1279,
 'speed': 3443,
 'limit': 2086,
 'display': 1033,
 'isnt': 1900,
 'money': 2366,
 'inexpensive': 1835,
 'plenty': 2697,
 'august': 305,
 '6': 114,
 '2009': 49,
 'glitch': 1486,
 'far': 1299,
 'amazingly': 237,
 'fast': 1303,
 'vehicle': 3873,
 'post': 2733,
 'im': 1788,
 'guilty': 1614,
 'pay': 2614,
 'attention': 297,
 'especially': 1190,
 'w': 3913,
 'trap': 3736,
 'constantly': 830,
 'change': 617,
 '2': 30,
 'weeks': 3959,
 'mistake': 2355,
 'completely': 786,
 'work': 4021,
 'local': 2114,
 'drive': 1085,
 'roads': 3043,
 'havent': 1643,
 'continue': 838,
 'youre': 4063,
 'determine': 991,
 'yards': 4050,
 'best': 395,
 'business': 531,
 'airport': 221,
 'know': 1983,
 'areas': 270,
 'glad': 1484,
 'graphics': 1542,
 'mileage': 2324,
 'new': 2435,
 'set': 3289,
 'locations': 2151,
 'user': 3848,
 'friendly': 1427,
 'try': 3754,
 '10': 10,
 'years': 4053,
 'ago': 213,
 'boat': 455,
 'difficult': 1007,
 'poor': 2715,
 'assume': 289,
 'wasnt': 3934,
 'visit': 3900,
 'place': 2672,
 'excellent': 1213,
 'intuitive': 1889,
 'interface': 1867,
 'small': 3372,
 'ill': 1786,
 'explain': 1248,
 'operate': 2543,
 'lead': 2026,
 'ones': 2539,
 'fewer': 1337,
 'item': 1907,
 'date': 925,
 'mount': 2381,
 'easily': 1119,
 'original': 2556,
 'necessary': 2417,
 'believe': 390,
 'information': 1838,
 'simplicity': 3329,
 'operation': 2544,
 'notch': 2500,
 'ive use': 1915,
 'use gps': 3827,
 'point point': 2709,
 'point b': 2707,
 '0 5': 1,
 '5 star': 105,
 '100 accurate': 16,
 'nice feature': 2453,
 'feature accurate': 1315,
 'pretty accurate': 2750,
 'review state': 3014,
 'depend use': 971,
 'screen easy': 3183,
 'easy voice': 1135,
 'voice tell': 3909,
 'tell accurate': 3631,
 'miss turn': 2354,
 'update latest': 3809,
 'blow away': 448,
 'use day': 3824,
 'day buy': 929,
 'buy morning': 544,
 'morning soon': 2375,
 'soon come': 3415,
 'come ready': 732,
 'ready navigate': 2895,
 'navigate downfall': 2403,
 'downfall product': 1071,
 'product reason': 2797,
 'reason 5': 2921,
 'star fact': 3512,
 'fact speed': 1280,
 'speed limit': 3444,
 'limit display': 2087,
 'display road': 1037,
 'road isnt': 3039,
 'isnt 100': 1901,
 'far speed': 1301,
 'little disappoint': 2103,
 'post speed': 2734,
 'constantly change': 831,
 '2 weeks': 39,
 'estimate time': 1195,
 'time arrival': 3678,
 'tell turn': 3633,
 'turn turn': 3771,
 'turn directions': 3765,
 'im really': 1792,
 'like easy': 2076,
 'easy read': 1131,
 'voice use': 3911,
 'garmin 255w': 1464,
 'easy set': 1132,
 'user friendly': 3849,
 'years ago': 4054,
 'difficult use': 1008,
 'directions map': 1019,
 'map easy': 2267,
 'easy use': 1134,
 'easy operate': 1129,
 'room': 3049,
 'overly': 2573,
 'big': 419,
 'clean': 663,
 'comfortable': 740,
 'bed': 380,
 'shower': 3313,
 'bathrooms': 356,
 'second': 3220,
 'smaller': 3387,
 'inconvenient': 1823,
 'bathroom': 351,
 'layout': 2021,
 'quieter': 2857,
 'sleep': 3362,
 'large': 2001,
 'wonderful': 4012,
 'comfy': 765,
 'spacious': 3428,
 'single': 3331,
 'sink': 3333,
 'standard': 3505,
 'motel': 2377,
 'upgrade': 3811,
 'remember': 2968,
 'perfectly': 2635,
 'form': 1399,
 'super': 3586,
 'eat': 1137,
 'floor': 1366,
 'door': 1062,
 'slightly': 3365,
 'larger': 2008,
 'spotless': 3452,
 'nicely': 2474,
 'appoint': 260,
 'exceptionally': 1227,
 'bite': 434,
 'dirty': 1021,
 'water': 3943,
 'tub': 3758,
 'initially': 1842,
 'wall': 3924,
 'toilet': 3698,
 'dog': 1050,
 'tend': 3635,
 'noisy': 2491,
 'fan': 1293,
 'noise': 2488,
 'whilst': 3975,
 'guest': 1610,
 'luxurious': 2227,
 'bathrobes': 349,
 'attend': 295,
 'beautiful': 377,
 'selection': 3227,
 'toiletries': 3699,
 'adequate': 182,
 'size': 3337,
 'smell': 3391,
 'decent': 943,
 'temperature': 3634,
 'pressure': 2748,
 'curtain': 905,
 'bar': 339,
 'hotel': 1708,
 'happy': 1630,
 'chill': 645,
 'drink': 1084,
 'view': 3890,
 'coit': 721,
 'tower': 3719,
 'king': 1979,
 'truly': 3752,
 'amenities': 240,
 'luxury': 2228,
 'property': 2812,
 'touch': 3708,
 'mini': 2335,
 'service': 3240,
 'wine': 3994,
 'reception': 2934,
 'light': 2068,
 'stock': 3549,
 'shampoo': 3297,
 'towel': 3718,
 'odd': 2517,
 'open': 2541,
 'hallway': 1621,
 'double': 1068,
 'include': 1818,
 'mirror': 2351,
 'abit': 140,
 'smallish': 3390,
 'immaculately': 1798,
 'maintain': 2239,
 'tastefully': 3620,
 'decorate': 951,
 'facilities': 1277,
 'space': 3427,
 'bedroom': 386,
 'fully': 1441,
 'need': 2420,
 'maintenance': 2240,
 'measure': 2292,
 'counter': 868,
 'maybe': 2287,
 'theyre': 3657,
 'bother': 477,
 'virtually': 3896,
 'slight': 3364,
 'worth': 4034,
 'complain': 781,
 'private': 2783,
 'tuscan': 3774,
 'inn': 1846,
 'chair': 612,
 'tv': 3776,
 'reasonably': 2925,
 'real': 2896,
 'complaint': 783,
 'separate': 3237,
 'vanity': 3865,
 'area': 266,
 'people': 2625,
 'dress': 1083,
 'kind': 1974,
 'surprise': 3597,
 'help': 1654,
 'create': 887,
 'reality': 2900,
 'cramp': 883,
 'hand': 1622,
 'particularly': 2607,
 'awkward': 328,
 'mention': 2302,
 'directly': 1020,
 'outside': 2561,
 'mean': 2291,
 'middle': 2322,
 'night': 2479,
 'wooden': 4019,
 'instal': 1859,
 'traditional': 3727,
 'add': 176,
 'hotels': 1748,
 'theme': 3653,
 'absolutely': 147,
 'dark': 919,
 'sun': 3583,
 'hairdryer': 1618,
 'wash': 3933,
 'acceptable': 152,
 'problems': 2789,
 'bigger': 428,
 'tiny': 3689,
 'modern': 2362,
 'tons': 3704,
 'perfect': 2630,
 'possible': 2731,
 'crack': 882,
 'ask': 281,
 'different': 1005,
 'fresh': 1418,
 'phone': 2656,
 'didnt': 996,
 'handle': 1623,
 'loose': 2187,
 'thermostat': 3656,
 'properly': 2811,
 'represent': 2982,
 'value': 3863,
 'impeccably': 1802,
 'linen': 2094,
 'daily': 915,
 'staff': 3463,
 'helpful': 1655,
 'usual': 3852,
 'chance': 615,
 'experience': 1245,
 'avoid': 319,
 'hit': 1689,
 'joke': 1922,
 'prefer': 2742,
 'bright': 500,
 'sell': 3232,
 'list': 2097,
 'bottle': 478,
 'wrong': 4045,
 'rest': 2999,
 'decor': 948,
 'okay': 2534,
 'price': 2758,
 'fell': 1333,
 'reasonable': 2923,
 'allow': 228,
 'book': 459,
 '4': 88,
 'minor': 2342,
 'downside': 1075,
 'shin': 3303,
 'negative': 2427,
 'suite': 3580,
 'older': 2538,
 'face': 1276,
 'lift': 2067,
 'compare': 778,
 'free': 1409,
 'bonus': 458,
 'big clean': 420,
 'clean comfortable': 670,
 'comfortable bed': 742,
 'bed great': 383,
 'room smaller': 3120,
 'large comfortable': 2004,
 'comfortable room': 756,
 'room wonderful': 3133,
 'bathroom room': 355,
 'room nice': 3101,
 'comfy bed': 766,
 'bed clean': 381,
 'clean bathroom': 666,
 'spacious clean': 3429,
 'large room': 2005,
 'room standard': 3125,
 'room like': 3091,
 'room quite': 3112,
 'quite small': 2864,
 'bathroom door': 353,
 'exceptionally clean': 1228,
 'bathroom clean': 352,
 'clean bed': 667,
 'provide great': 2817,
 'bed comfortable': 382,
 'clean nice': 680,
 'nice selection': 2466,
 'adequate size': 183,
 'room bed': 3058,
 'room bathrooms': 3057,
 'bar hotel': 340,
 'hotel happy': 1726,
 'coit tower': 722,
 'room small': 3119,
 'king bed': 1980,
 'nice touch': 2471,
 'mini bar': 2336,
 'bar room': 341,
 'room service': 3117,
 'wine reception': 3997,
 'odd thing': 2518,
 'door room': 1065,
 'door open': 1064,
 'room spacious': 3122,
 '2 double': 34,
 'double bed': 1069,
 'bed plenty': 384,
 'plenty room': 2700,
 'good size': 1522,
 'room large': 3089,
 'large clean': 2003,
 'clean appoint': 664,
 'big room': 425,
 'room need': 3100,
 'tuscan inn': 3775,
 'inn room': 1850,
 'real complaint': 2898,
 'try use': 3756,
 'come room': 733,
 'room good': 3081,
 'small bathroom': 3373,
 'bathrooms nice': 358,
 'room view': 3130,
 'tiny bathroom': 3690,
 'modern room': 2363,
 'room pretty': 3109,
 'room bathroom': 3056,
 'perfect size': 2634,
 'size just': 3344,
 'just need': 1940,
 'different room': 1006,
 'room clean': 3063,
 'clean fresh': 673,
 'fresh small': 1421,
 'didnt work': 1000,
 'work bathroom': 4022,
 'door handle': 1063,
 'handle quite': 1624,
 'work properly': 4028,
 'represent value': 2983,
 'value money': 3864,
 'money room': 2369,
 'bathrooms impeccably': 357,
 'impeccably clean': 1803,
 'fresh linen': 1420,
 'linen daily': 2095,
 'daily staff': 916,
 'staff extremely': 3477,
 'extremely helpful': 1271,
 'helpful friendly': 1657,
 'really didnt': 2904,
 'didnt chance': 997,
 'chance experience': 616,
 'experience staff': 1247,
 'staff level': 3487,
 'level service': 2044,
 'service room': 3280,
 'nice use': 2472,
 'use just': 3830,
 'just little': 1937,
 'room reasonable': 3114,
 'reasonable price': 2924,
 'price hotel': 2763,
 'allow book': 229,
 'book 2': 460,
 '2 room': 38,
 'nice clean': 2451,
 'clean room': 683,
 'little small': 2105,
 'hotel good': 1724,
 'good standard': 1525,
 'standard big': 3506,
 'room decent': 3069,
 'decent bathroom': 944,
 'bathroom free': 354,
 'free wine': 1412,
 'reception add': 2935,
 'add bonus': 177,
 'plug': 2701,
 'usb': 3819,
 'computer': 797,
 'charge': 621,
 'cord': 855,
 'design': 975,
 'page': 2583,
 '500': 108,
 '15': 21,
 'excite': 1231,
 'low': 2214,
 'unless': 3799,
 'extend': 1251,
 'warranty': 3932,
 '65': 120,
 'year': 4051,
 'ship': 3304,
 'send': 3233,
 'device': 992,
 'amazon': 238,
 'kindle': 1976,
 'replace': 2978,
 'sd': 3208,
 'card': 587,
 'issue': 1904,
 'things': 3661,
 'button': 536,
 'accidentally': 157,
 'cursor': 904,
 'select': 3226,
 'hard': 1632,
 'occasionally': 2515,
 'menus': 2308,
 'case': 595,
 'practically': 2740,
 'force': 1396,
 'remove': 2973,
 'pull': 2824,
 'eliminate': 1158,
 'wrap': 4042,
 'sleek': 3361,
 'slot': 3368,
 'admit': 193,
 'actually': 172,
 'car': 570,
 'charger': 623,
 'port': 2720,
 'carry': 592,
 'extra': 1257,
 'life': 2049,
 'options': 2548,
 'non': 2492,
 'ipod': 1893,
 'fix': 1357,
 'theres': 3654,
 'power': 2737,
 'purchase': 2826,
 'border': 474,
 'lack': 1988,
 'touchscreen': 3712,
 'keyboard': 1960,
 'faster': 1307,
 'flip': 1364,
 'high': 1670,
 'fine': 1345,
 'c': 548,
 'k2': 1954,
 'short': 3309,
 'couple': 870,
 'hours': 1758,
 '24': 53,
 'run': 3145,
 '75': 125,
 'notice': 2503,
 'half': 1619,
 'way': 3944,
 'fourth': 1404,
 'icon': 1777,
 'stink': 3548,
 'box': 483,
 'immediately': 1800,
 'log': 2154,
 'begin': 389,
 'download': 1072,
 'weight': 3961,
 'attractive': 302,
 'data': 924,
 'storage': 3552,
 'longer': 2167,
 'usage': 3818,
 'k1': 1953,
 'cut': 911,
 'significantly': 3323,
 'week': 3956,
 'order': 2550,
 'deliver': 967,
 'critical': 892,
 'wireless': 4002,
 'minutes': 2348,
 'enable': 1161,
 'likely': 2085,
 'hold': 1691,
 'color': 726,
 '200': 42,
 'memory': 2300,
 'constant': 829,
 'shorter': 3311,
 'guess': 1609,
 'batteries': 359,
 'wish': 4008,
 'removable': 2971,
 'cover': 879,
 'store': 3553,
 'clerk': 699,
 'restart': 3000,
 'spot': 3451,
 'days': 935,
 'normal': 2495,
 'save': 3162,
 'menu': 2303,
 'option': 2547,
 'perceptible': 2629,
 'drain': 1080,
 'sony': 3413,
 '60': 116,
 'main': 2235,
 'youd': 4060,
 'clear': 693,
 'advantage': 196,
 'long': 2159,
 'spare': 3431,
 'handy': 1625,
 'clip': 701,
 'access': 153,
 'recharge': 2939,
 'let': 2038,
 'finally': 1343,
 'fail': 1284,
 'wont': 4016,
 'apparently': 253,
 'cell': 601,
 'end': 1163,
 'right': 3029,
 'backlight': 332,
 'hardly': 1637,
 'definitely': 958,
 '3': 71,
 'idea': 1781,
 'important': 1804,
 'offset': 2527,
 'improve': 1811,
 'probably': 2784,
 'wouldnt': 4039,
 '20': 40,
 'iphone': 1892,
 'netbook': 2430,
 'tradeoff': 3725,
 'ipods': 1897,
 'oh': 2528,
 'wifi': 3984,
 '25': 58,
 'code': 713,
 'general': 1474,
 'check': 629,
 'warn': 3931,
 '55': 109,
 'maximum': 2286,
 'live': 2109,
 'uk': 3783,
 'expense': 1241,
 'cable': 551,
 'unbelievable': 3785,
 'plane': 2683,
 'simple': 3328,
 'love': 2200,
 'cool': 853,
 'pics': 2663,
 'gadget': 1454,
 'factor': 1281,
 'advertise': 197,
 'title': 3695,
 'readable': 2891,
 'network': 2434,
 'battery charge': 364,
 'book page': 465,
 'replace battery': 2979,
 'kindle 2': 1978,
 'things like': 3663,
 'make easy': 2243,
 'accidentally turn': 158,
 'turn page': 3766,
 'change battery': 618,
 'kindle 1': 1977,
 'actually need': 173,
 'battery charger': 365,
 'usb port': 3820,
 'battery life': 368,
 'keyboard layout': 1966,
 'super high': 3587,
 '24 hours': 55,
 'light weight': 2069,
 'life better': 2052,
 'use feature': 3825,
 'life good': 2057,
 'good wireless': 1530,
 'use battery': 3822,
 'battery longer': 369,
 'battery battery': 362,
 'good thing': 1527,
 'life pretty': 2063,
 '2 days': 33,
 'turn wireless': 3773,
 'like fact': 2077,
 'battery drain': 367,
 'drain battery': 1081,
 'removable battery': 2972,
 'longer battery': 2168,
 'life long': 2061,
 'long day': 2161,
 'screen small': 3202,
 'battery doesnt': 366,
 'doesnt long': 1047,
 'long use': 2166,
 '2 hours': 35,
 'long time': 2164,
 'cell phone': 602,
 '3 hours': 72,
 'battery 4': 361,
 'better battery': 402,
 'far better': 1300,
 '4 hours': 94,
 '5 6': 102,
 '6 hours': 115,
 'touch screen': 3710,
 'memory card': 2301,
 'turn wifi': 3772,
 'know need': 1984,
 'use lot': 3833,
 'lot battery': 2191,
 'battery use': 371,
 'use computer': 3823,
 'life unbelievable': 2066,
 'book download': 461,
 'life great': 2058,
 'long battery': 2160,
 'life amaze': 2050,
 'amaze battery': 234,
 'scratch': 3170,
 'wonder': 4011,
 'slide': 3363,
 'control': 843,
 'shut': 3315,
 'portable': 2723,
 'quality': 2830,
 '5g': 110,
 'lie': 2047,
 'mature': 2283,
 'step': 3542,
 'wiser': 4006,
 'old': 2535,
 'gain': 1456,
 'incremental': 1828,
 'improvements': 1813,
 'brighter': 503,
 'video': 3882,
 'appeal': 254,
 'aspect': 283,
 'tantalize': 3615,
 '249': 56,
 '30gb': 79,
 'version': 3877,
 '349': 83,
 'huge': 1767,
 '80gb': 131,
 'rat': 2875,
 'proof': 2810,
 'record': 2944,
 'watch': 3938,
 'listen': 2098,
 'music': 2394,
 'picture': 2664,
 'radio': 2869,
 'christmas': 653,
 'son': 3412,
 'replacement': 2980,
 'eventually': 1202,
 'apples': 258,
 'instead': 1862,
 'exchange': 1230,
 'newer': 2443,
 'convenient': 845,
 'pedometer': 2623,
 'gift': 1480,
 'recommend': 2940,
 'exactly': 1211,
 'wifes': 3983,
 'favorite': 1311,
 'past': 2611,
 'camera': 560,
 'speaker': 3435,
 'expect': 1236,
 'die': 1002,
 'quicker': 2848,
 'cold': 723,
 'weather': 3951,
 'videos': 3889,
 'catch': 597,
 'audio': 304,
 'possibly': 2732,
 'greater': 1594,
 'outlet': 2558,
 'present': 2745,
 'sound': 3418,
 'deal': 937,
 'lcd': 2024,
 'snap': 3404,
 'previous': 2755,
 '2nd': 69,
 'gen': 1472,
 'nano': 2398,
 'auto': 306,
 'library': 2046,
 '2gb': 68,
 'bad': 334,
 '8': 129,
 'shoe': 3306,
 'cam': 559,
 'kill': 1973,
 'sharp': 3300,
 '3rd': 87,
 'generation': 1478,
 '5th': 112,
 'twice': 3777,
 'number': 2506,
 'suggest': 3577,
 'overall': 2564,
 'freeze': 1414,
 'lightweight': 2071,
 'tune': 3763,
 'station': 3520,
 'burn': 527,
 'addition': 178,
 'strong': 3564,
 'compact': 775,
 'performance': 2637,
 'gym': 1616,
 'classic': 661,
 'toll': 3700,
 'dont use': 1061,
 'im use': 1795,
 'good quality': 1517,
 '5g lie': 111,
 'lie mature': 2048,
 'mature ipod': 2284,
 'ipod step': 1896,
 'step wiser': 3543,
 'wiser able': 4007,
 'able year': 143,
 'year old': 4052,
 'old ipod': 2537,
 'ipod gain': 1894,
 'gain incremental': 1457,
 'incremental improvements': 1829,
 'improvements include': 1814,
 'include brighter': 1819,
 'brighter screen': 504,
 'screen better': 3174,
 'better video': 413,
 'video battery': 3883,
 'life probably': 2064,
 'probably appeal': 2785,
 'appeal aspect': 255,
 'aspect tantalize': 284,
 'tantalize price': 3616,
 'price point': 2769,
 'point 249': 2706,
 '249 30gb': 57,
 '30gb version': 80,
 'version 349': 3878,
 '349 huge': 84,
 'huge 80gb': 1768,
 '80gb version': 132,
 'love color': 2202,
 'new ipod': 2439,
 'watch video': 3941,
 'just listen': 1936,
 'listen music': 2099,
 'time good': 3680,
 'just use': 1949,
 'isnt great': 1903,
 'highly recommend': 1678,
 'great new': 1571,
 'build speaker': 521,
 'use great': 3828,
 'great battery': 1545,
 'cold weather': 724,
 'watch videos': 3942,
 'battery quickly': 370,
 ...}

KMeans 군집화

In [39]:
from sklearn.cluster import KMeans

kmeans = KMeans( 
    n_clusters = 4,    # 군집 개수
    max_iter = 5000,  # 반복 횟수
    random_state = 0  # 시드 고정
)

opinions_label = kmeans.fit_predict(opinions_vecs) 
document_df['cluster'] = opinions_label
document_df

,filename,opinions,cluster
0,accuracy_garmin_nuvi_255W_gps,...,2
1,bathroom_bestwestern_hotel_sfo,...,1
2,battery-life_amazon_kindle,...,0
3,battery-life_ipod_nano_8gb,...,2
4,battery-life_netbook_1005ha,...,2
5,buttons_amazon_kindle,...,0
6,comfort_honda_accord_2008,...,3
7,comfort_toyota_camry_2007,...,3
8,directions_garmin_nuvi_255W_gps,...,2
9,display_garmin_nuvi_255W_gps,...,2
10,eyesight-issues_amazon_kindle,...,0
11,features_windows7,...,2
12,fonts_amazon_kindle,...,0
13,food_holiday_inn_london,...,1
14,food_swissotel_chicago,...,1
15,free_bestwestern_hotel_sfo,...,1
16,gas_mileage_toyota_camry_2007,...,3
17,interior_honda_accord_2008,...,3
18,interior_toyota_camry_2007,...,3
19,keyboard_netbook_1005ha,...,2
20,location_bestwestern_hotel_sfo,...,1
21,location_holiday_inn_london,...,1
22,mileage_honda_accord_2008,...,3
23,navigation_amazon_kindle,...,0
24,parking_bestwestern_hotel_sfo,...,1
25,performance_honda_accord_2008,...,3
26,performance_netbook_1005ha,...,2
27,price_amazon_kindle,...,0
28,price_holiday_inn_london,...,0
29,quality_toyota_camry_2007,...,3
30,rooms_bestwestern_hotel_sfo,...,1
31,rooms_swissotel_chicago,...,1
32,room_holiday_inn_london,...,1
33,satellite_garmin_nuvi_255W_gps,...,2
34,screen_garmin_nuvi_255W_gps,...,2
35,screen_ipod_nano_8gb,...,2
36,screen_netbook_1005ha,...,2
37,seats_honda_accord_2008,...,3
38,service_bestwestern_hotel_sfo,...,1
39,service_holiday_inn_london,...,1
40,service_swissotel_hotel_chicago,...,1
41,size_asus_netbook_1005ha,...,2
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it and ...,2
43,speed_garmin_nuvi_255W_gps,...,2
44,speed_windows7,...,0
45,staff_bestwestern_hotel_sfo,...,1
46,staff_swissotel_chicago,...,1
47,transmission_toyota_camry_2007,...,3
48,updates_garmin_nuvi_255W_gps,...,2
49,video_ipod_nano_8gb,...,2
50,voice_garmin_nuvi_255W_gps,...,2

In [44]:
# 클러스터 중심 키워드(상위 TF-IDF) 추출
centers = kmeans.cluster_centers_  #각 클러스터별 중심 벡터
print(centers.shape)               # (클러스터 수, 특성 수)

centroid_arg_idx = centers.argsort()[:,::-1]  # 각 클러스터별 특성값 기준 내림차순하여 인덱스 반환
top_20 = centroid_arg_idx[ : : 20]            # 클러스터별 상위 20개 인덱스
feature_names = tfidf_vectorizer.get_feature_names_out()
feature_names[top_20]

(4, 4072)

array([['kindle', 'price', 'page', ..., '1 block', '2 weeks', '2 1']],
      shape=(1, 4072), dtype=object)